package com.pratiksymz.tracker_domain.use_case

import com.pratiksymz.tracker_domain.model.MealType
import com.pratiksymz.tracker_domain.model.TrackableFood
import com.pratiksymz.tracker_domain.model.TrackedFood
import com.pratiksymz.tracker_domain.repository.TrackerRepository
import java.time.LocalDate
import kotlin.math.roundToInt

/**
 * This use case is responsible for tracking (adding) a food item (TrackableFood) into one of our Meal Types.
 */
class TrackFood(
    private val repository: TrackerRepository
) {
    /**
     * @param amount Total amount of food in grams
     */
    suspend operator fun invoke(
        food: TrackableFood,
        amount: Int,
        mealType: MealType,
        date: LocalDate
    ) {
        repository.insertTrackedFood(
            // id -> Auto-generated by Room
            TrackedFood(
                name = food.name,
                carbs = ((food.carbsPer100g / 100f) * amount).roundToInt(),
                protein = ((food.proteinPer100g / 100f) * amount).roundToInt(),
                fat = ((food.fatPer100g / 100f) * amount).roundToInt(),
                calories = ((food.caloriesPer100g / 100f) * amount).roundToInt(),
                imageUrl = food.imageUrl,
                mealType = mealType,
                amount = amount,
                date = date
            )
        )
    }
}