package com.pratiksymz.tracker_data.local.entity

import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity
data class TrackedFoodEntity(
    @PrimaryKey val id: Int? = null,    // Auto-generated by Room
    val name: String,
    val carbs: Int,
    val protein: Int,
    val fat: Int,
    val imageUrl: String?,
    val mealType: String,    // Breakfast, Snack, Lunch, or Dinner
    val amount: Int,        // Amount in grams of Food item
    val dayOfMonth: Int,
    val month: Int,
    val year: Int,
    val calories: Int
)
